name = "'Dustrial Decor"
filename = "DustrialDecor-1.3.1-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/764/DustrialDecor-1.3.1-1.18.jar"
hash-format = "murmur2"
hash = "4168309420"

[update]
[update.curseforge]
file-id = 3549764
project-id = 401273
