name = "Farming for Blockheads"
filename = "farmingforblockheads-forge-1.18.1-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/204/farmingforblockheads-forge-1.18.1-9.0.3.jar"
hash-format = "murmur2"
hash = "2676812724"

[update]
[update.curseforge]
file-id = 3606204
project-id = 261924
