name = "Mystical Agriculture Tiered Crystals"
filename = "matc-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/230/matc-1.2.0.jar"
hash-format = "murmur2"
hash = "1153055990"

[update]
[update.curseforge]
file-id = 3570230
project-id = 299045
