name = "Refined Storage"
filename = "refinedstorage-1.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/324/refinedstorage-1.10.0.jar"
hash-format = "murmur2"
hash = "325003788"

[update]
[update.curseforge]
file-id = 3623324
project-id = 243076
