name = "RFTools Utility"
filename = "rftoolsutility-1.18-4.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/743/rftoolsutility-1.18-4.0.6.jar"
hash-format = "murmur2"
hash = "1675217873"

[update]
[update.curseforge]
file-id = 3604743
project-id = 342466
